### ISSUE TITLE
Error: command not found

### ISSUE THREAD

**Issue by natinusala** [Cesura/nxsh#1]
Switch on 5.1.0, PC on Windows 10 using PuTTY - the shell works well but each time I enter a command (or enter the shell) I have an "Error: command not found" message :

https://puu.sh/BV22U/ca84966245.png

**Comment by Cesura** [comment]
Thanks for the report. I looked into it and seem to have solved the problem, so check out version 0.1.2-alpha and see if that helps you.

Note that when connecting via telnet in PuTTY, the "command not found" message that is sent immediately as the shell starts is a result of some negotiation within the telnet protocol being misinterpreted as a command. I've had much better luck connecting through putty with the "raw" option, so I'd recommend others to try that as well.

**Comment by natinusala** [comment]
Indeed it's fixed now, thanks
