### ISSUE TITLE
Make it feel more like bash?

### ISSUE THREAD

**Issue by fennectech** [Cesura/nxsh#3]
Can we make the console feel like bash?   And print out the log on the switch's screen too

**Comment by Cesura** [comment]
Could you elaborate on what you mean by "more like bash"? As for the second part, I could add a toggle that would enable printing of all the entered commands on the Switch's screen itself, if that would be helpful.

**Comment by fennectech** [comment]
Bash has a prompt like
user@host:path $ and the user types commands after thato
so  for example
fennectech@switch:sdmc:/modules/$

**Comment by fennectech** [comment]
Can we also log to a file in /modules/logs

**Comment by Cesura** [comment]
Thanks for the suggestions. Check out release 0.1.4-alpha; it should hopefully include what you were looking for. :)

**Comment by fennectech** [comment]
Awesome I’ll check it out in the morning
