### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fennectech** [Cesura/nxsh#5]
i recommend storing nxsh's files in the switch folder along with nxsh.nro in a subfolder   so like /switch/nxsh/nxsh.pw and /switch/nxsh/nxsh.nro

**Comment by Cesura** [comment]
I can use /switch/nxsh for password/logging if that would be more logical, but I sadly can't control where the user places the .nro file on their SD card.

**Comment by friedkeenan** [comment]
One issue with this might be when this is implemented as a kip (I've made marginal progress on that). It wouldn't really make sense for a sysmodule to be storing files in homebrew folders

**Comment by fennectech** [comment]
Why not simply load them from the same directory the nro/kip is in.  That way if the user oads it as a kip it loads from the same DIR.

**Comment by friedkeenan** [comment]
You would have to look through the SD card until you found the kip/nro, which is more work than just having it be the same for both

**Comment by fennectech** [comment]
oi   well howabout a folder in /modules/ for the kip version
